/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'micheltabari' at '2015-11-30 21:16' with Gradle 2.9
 *
 * @author micheltabari, @date 2015-11-30 21:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
